spring:
  profiles:
    active: local
    group:
      "local": "localPort, localDB, localS3, localSecret"
      "dev": "devPort, devDB, devS3, devSecret"
      "prod": "prodPort, prodDB, prodS3, prodSecret"
---
