spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/togedy
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8081
